#!/bin/bash

# Packages
set -eux

if [[ $(uname) = 'Darwin' ]]; then

  which brew || ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

  brew update

  which git || brew install git

  which ag || brew install the_silver_searcher

  which tmux || brew install tmux

  which nvim || brew install neovim

  [[ $SHELL = "/bin/zsh" ]] || (
    brew install zsh;
    sudo chsh -s /bin/zsh `whoami`
  )

else

  sudo apt-get update -y

  sudo apt-get install -y software-properties-common

  which git || sudo apt-get install -y git

  which ag || (
    sudo apt-get install -y silversearcher-ag;
    sudo dpkg-divert --local --divert /usr/bin/ag --rename --add /usr/bin/silversearcher-ag
  )

  which tmux || sudo apt-get install -y tmux

  which zsh || sudo apt-get install -y zsh

  which neovim || (
    sudo add-apt-repository ppa:neovim-ppa/stable;
    sudo apt-get update -y;
    sudo apt-get install -y neovim
  )

fi

# Symlinks
set +ex

for source in $(find ~/.config/msauter/*/linked -type f); do
  target=~/$(basename "$source")
  echo "ln -s $source $target"
  ln -s $source $target
done

echo "ln -s /Applications/Sublime Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime"
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
