#!/bin/bash

# Packages
set -eux

if [[ $(uname) = 'Darwin' ]]; then

  which brew || ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

  brew update

  which git || brew install git

  which ag || brew install the_silver_searcher

  which tmux || brew install tmux

  which nvim || brew install neovim

  which go || (
    curl -O https://dl.google.com/go/go1.10.darwin-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.10.darwin-amd64.tar.gz
    rm go1.10.darwin-amd64.tar.gz
  )

  which 2fa || /usr/local/go/bin/go get -u rsc.io/2fa

  which pwgen || brew install pwgen

  which jq || brew install jq

  [[ $SHELL = "/bin/zsh" ]] || (
    brew install zsh;
    sudo chsh -s /bin/zsh `whoami`
  )

else

  sudo apt-get update -y

  sudo apt-get install -y software-properties-common

  which git || sudo apt-get install -y git

  which ag || (
    sudo apt-get install -y silversearcher-ag;
    sudo dpkg-divert --local --divert /usr/bin/ag --rename --add /usr/bin/silversearcher-ag
  )

  which tmux || sudo apt-get install -y tmux

  which zsh || sudo apt-get install -y zsh

  which nvim || (
    sudo add-apt-repository ppa:neovim-ppa/stable;
    sudo apt-get update -y;
    sudo apt-get install -y neovim
  )

  which go || (
    curl -O https://dl.google.com/go/go1.10.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.10.linux-amd64.tar.gz
    rm go1.10.linux-amd64.tar.gz
  )

  which 2fa || /usr/local/go/bin/go get -u rsc.io/2fa

  which jq || sudo apt-get install jq
fi

set +ex

# Symlinks
for source in $(find ~/.config/msauter/*/linked -type f); do
  target=~/$(basename "$source")
  echo "ln -sf $source $target"
  ln -sf $source $target
done
if [[ $(uname) = 'Darwin' ]]; then
  echo "ln -sf /Applications/Sublime Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime"
  ln -sf "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
else
  echo "ln -sf /opt/sublime_text/sublime_text /usr/local/bin/sublime"
  ln -sf /opt/sublime_text/sublime_text /usr/local/bin/sublime
fi

# Copies
# for source in $(find ~/.config/msauter/*/copied -type f); do
#   target=~/$(basename "$source")
#   echo "cp $source $target"
#   cp $source $target
# done

# Theme
base16_eighties
