#!/bin/bash

# Packages
set -eux

if [[ $(uname) = 'Darwin' ]]; then

  which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew update

  which git || brew install git

  which ag || brew install the_silver_searcher

  which tmux || brew install tmux

  which nvim || brew install neovim

  which go || (
    curl -O https://dl.google.com/go/go1.13.darwin-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.13.darwin-amd64.tar.gz
    rm go1.13.darwin-amd64.tar.gz
  )

  which 2fa || /usr/local/go/bin/go install rsc.io/2fa@latest

  which pwgen || brew install pwgen

  which jq || brew install jq

  which bat || brew install bat
  
  which mkcert || brew install mkcert

  which rlwrap || brew install rlwrap

  which yaegi || /usr/local/go/bin/go install github.com/traefik/yaegi/cmd/yaegi@latest

  [[ $SHELL = "/bin/zsh" ]] || (
    brew install zsh;
    sudo chsh -s /bin/zsh `whoami`
  )

else

  sudo apt-get update -y

  sudo apt-get install -y software-properties-common

  which git || sudo apt-get install -y git

  which ag || (
    sudo apt-get install -y silversearcher-ag;
    sudo dpkg-divert --local --divert /usr/bin/ag --rename --add /usr/bin/silversearcher-ag
  )

  which tmux || sudo apt-get install -y tmux

  which zsh || sudo apt-get install -y zsh

  which nvim || (
    sudo add-apt-repository ppa:neovim-ppa/stable;
    sudo apt-get update -y;
    sudo apt-get install -y neovim
  )

  which go || (
    curl -O https://dl.google.com/go/go1.13.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.13.linux-amd64.tar.gz
    rm go1.13.linux-amd64.tar.gz
  )

  which 2fa || /usr/local/go/bin/go install rsc.io/2fa@latest

  which yaegi || /usr/local/go/bin/go install github.com/traefik/yaegi/cmd/yaegi@latest

  which jq || sudo apt-get install jq
fi

# Symlinks
set +ex

for source in $(find ~/.config/msauter/*/linked -type f); do
  target=~/$(basename "$source")
  echo "ln -sf $source $target"
  ln -sf $source $target
done

if [[ $(uname) = 'Darwin' ]]; then
  echo "ln -sf /Applications/Sublime Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime"
  ln -sf "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
else
  echo "ln -sf /opt/sublime_text/sublime_text /usr/local/bin/sublime"
  ln -sf /opt/sublime_text/sublime_text /usr/local/bin/sublime
fi

# Theme
base16_eighties

echo "Done."
